version: '3.8'

services:
  example-frontend:
    image: devopsdocker/example-frontend
    build:
      context: ~/Data/devOpsDocker/material-applications/example-frontend
      dockerfile: ./Dockerfile
    container_name: devopsdocker_example_frontend
    ports:
      - '4000:4000'
  example-backend:
    image: devopsdocker/example-backend
    build:
      context: ~/Data/devOpsDocker/material-applications/example-backend
      dockerfile: ./Dockerfile
    container_name: devopsdocker_example_backend
    ports:
      - '8080:8080'
    environment:
      - REQUEST_ORIGIN=http://localhost:4000